version: '2'

services:
  node_exporter:
    image: prom/node-exporter
    container_name: prom_9100
    ports:
      - "9100:9100"
    command: ["-collectors.enabled=diskstats,filesystem,loadavg,meminfo,netdev,netstat,stat,time,uname,vmstat"]
    network_mode: host

  mysqld_exporter_high_res:
    image: prom/mysqld-exporter
    container_name: prom_9104
    volumes:
      - ./my.cnf:/opt/.my.cnf
    ports:
      - "9104:9104"
    command: ["-web.listen-address=:9104", "-config.my-cnf=/opt/.my.cnf", "-collect.global_status=true", "-collect.global_variables=false", "-collect.slave_status=false", "-collect.info_schema.tables=false", "-collect.binlog_size=false", "-collect.info_schema.processlist=false", "-collect.info_schema.userstats=false", "-collect.info_schema.tables=false", "-collect.auto_increment.columns=false", "-collect.info_schema.tablestats=false", "-collect.perf_schema.file_events=false", "-collect.perf_schema.eventsstatements=false", "-collect.perf_schema.indexiowaits=false", "-collect.perf_schema.tableiowaits=false", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=false"]
    network_mode: host

  mysqld_exporter_med_res:
    image: prom/mysqld-exporter
    container_name: prom_9105
    volumes:
      - ./my.cnf:/opt/.my.cnf
    ports:
      - "9105:9105"
    command: ["-web.listen-address=:9105", "-config.my-cnf=/opt/.my.cnf", "-collect.global_status=false", "-collect.global_variables=false", "-collect.slave_status=true", "-collect.info_schema.tables=false", "-collect.binlog_size=false", "-collect.info_schema.processlist=true", "-collect.info_schema.userstats=false", "-collect.info_schema.tables=false", "-collect.auto_increment.columns=false", "-collect.info_schema.tablestats=false", "-collect.perf_schema.file_events=true", "-collect.perf_schema.eventsstatements=false", "-collect.perf_schema.indexiowaits=false", "-collect.perf_schema.tableiowaits=false", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=true"]
    network_mode: host

  mysqld_exporter_low_res:
    image: prom/mysqld-exporter
    container_name: prom_9106
    volumes:
      - ./my.cnf:/opt/.my.cnf
    ports:
      - "9106:9106"
    command: ["-web.listen-address=:9106", "-config.my-cnf=/opt/.my.cnf", "-collect.global_status=false", "-collect.global_variables=true", "-collect.slave_status=false", "-collect.info_schema.tables=true", "-collect.binlog_size=false", "-collect.info_schema.processlist=false", "-collect.info_schema.userstats=true", "-collect.info_schema.tables=true", "-collect.auto_increment.columns=true", "-collect.info_schema.tablestats=true", "-collect.perf_schema.file_events=false", "-collect.perf_schema.eventsstatements=true", "-collect.perf_schema.indexiowaits=true", "-collect.perf_schema.tableiowaits=true", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=false"]
    network_mode: host

